dist: xenial
sudo: false
language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - gcc-4.8
      - unixodbc-dev
install:
  - pip install pycodestyle
before_script:
  - pip install coveralls
  - npm install
  - pip install .
  - cp travis/manage.py manage.py
script:
  - pycodestyle mongo_rest/ --exclude=migrations,mongo_rest/static
  - ./node_modules/.bin/stylelint '**/*.vue' '**/*.css' '**/*.scss'
  - ./node_modules/.bin/eslint --ext .js,.vue mongo_rest/static/mongo_rest/js/components/
  - ./node_modules/.bin/eslint --ext .js,.vue mongo_rest/static/mongo_rest/js/pages/
  - coverage run --source=mongo_rest/ --omit=mongo_rest/migrations/* manage.py test mongo_rest
after_success:
  - coveralls
