version: '3.4'

services:
  app:
    build:
      context: .
      target: app-container
    restart: always
    container_name: mongo_rest_app
    environment:
      - GOOGLE_ANALYTICS_KEY=${GOOGLE_ANALYTICS_KEY}
    volumes:
      - ./mongo_rest:/app/mongo_rest
      - statics-volume:/static
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
    stdin_open: true
    tty: true
    networks:
      - app-tier
  node-bundler:
    build:
      context: .
      target: node-bundler
    restart: always
    container_name: mongo_rest_node
    ports:
      - "${BUNDLE_ANALYZER_PORT:-8888}:8888" # Required when environment.BUNDLE_ANALYZER is true
    environment:
      VUE_DEVTOOLS: "True"
      BUNDLE_ANALYZER: "True"
    volumes:
      - ./mongo_rest:/app/mongo_rest # expose main django app so vite can output bundles here
      - ./mongo_rest_vue:/app/mongo_rest_vue
      - statics-volume:/static
    command: npm run watch
    stdin_open: true
    tty: true
  db:
    container_name: mongo_rest_db
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - mongodb-volume:/data/db
    ports:
      - '27017:27017'
volumes:
  statics-volume:
  mongodb-volume:
