version: '3'

services:
  app:
    environment:
      - GOOGLE_ANALYTICS_KEY=${GOOGLE_ANALYTICS_KEY}
    restart: always
    container_name: mongo_rest_app
    build:
      context: .
    volumes:
      - ./mongo_rest:/app/mongo_rest
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
  devtools:
    restart: always
    container_name: mongo_rest_devtools
    image: node:8.16.0-jessie
    volumes:
      - ./package.json:/devtools/mongo-restapi/package.json
      - ./webpack.config.js:/devtools/mongo-restapi/webpack.config.js
      - ./mongo_rest:/devtools/mongo-restapi/mongo_rest
    working_dir: /devtools/mongo-restapi
    command: bash -c "yes yes | npm install; npx webpack --watch --mode=development"
