from django.urls import include, path, re_path
from django.views.generic.base import RedirectView
from mongo_rest.views.pages import PageView
from mongo_rest.views.api import SpotViewSet

from rest_framework import routers

# this is DRF router for REST API viewsets
router = routers.DefaultRouter()
router.register(r'spot', SpotViewSet, r"spot")

urlpatterns = [

    # REST API root view (generated by DRF router)
    path(r'api/', include(router.urls)),
    path('', PageView.as_view(), name='index'),
]
